// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/phase-change-diagram": {
            "get": {
                "description": "Retorna volumen específico de líquido y vapor en función de la presión.",
                "summary": "Obtener diagrama de cambio de fase",
                "parameters": [
                    {
                        "type": "number",
                        "format": "float",
                        "description": "Presión en MPa",
                        "name": "pressure",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.PhaseChangeResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.PhaseChangeResponse": {
            "type": "object",
            "properties": {
                "specific_volume_liquid": {
                    "type": "number"
                },
                "specific_volume_vapor": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Phase Change Diagram API",
	Description:      "API para obtener datos de volumen específico en función de la presión.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
